version: '2.1'
volumes:
  wireguard-config:
  apachefiles:
  apacheconfig:
services:
  apache:
    restart: always
    build: ./apache
    ports:
      - "8080:8080/udp"
      - "8080:8080/tcp"
    volumes:
      - apachefiles:/var/www
      - apacheconfig:/etc/apache2
  wireguard:
    build: ./balena-wireguard
    privileged: true
    volumes:
      - wireguard-config:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - io.balena.features.kernel-modules=1
            