version: "2.1"

volumes:
  config:

services:
  wireguard:
    build: .
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_MODULE
    environment:
      - SERVER_HOST=auto
      - SERVER_PORT=51820
      - PEERS=1
      - PEER_DNS=1.1.1.1
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0, ::0/0
    volumes:
      - config:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - io.balena.features.kernel-modules=1
      - io.balena.features.supervisor-api=1
