version: "2.1"

volumes:
  config:

services:
  wireguard:
    build: .
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_MODULE
    volumes:
      - config:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - io.balena.features.kernel-modules=1
      - io.balena.features.supervisor-api=1

  fbcp:
    image: balenablocks/fbcp
    privileged: true

  glances:
    image: klutchell/glances:3.1.7
    privileged: true
    network_mode: host
    pid: host
    labels:
      io.balena.features.dbus: "1"
    depends_on:
      - fbcp
