version: "2.1"

volumes:
  config:

services:
  wireguard:
    build: .
    privileged: true
    ports:
      - 51820:51820/udp
    volumes:
      - config:/config
    labels:
      io.balena.features.kernel-modules: '1'
