version: "2.1"

volumes:
  config:

services:
  web:
    image: vx3r/wg-gen-web:latest
    ports:
      - 80:8080/tcp
    volumes:
      - config:/data
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf

  wireguard:
    build: wireguard
    network_mode: host
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    #   - SYS_MODULE
    volumes:
      - config:/etc/wireguard
    labels:
      io.balena.features.kernel-modules: '1'
    sysctls:
      - net.ipv4.ip_forward=1
