version: "2.1"

volumes:
  config:

services:
  wireguard:
    build: .
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    # ports:
    #   - 51820:51820/udp
    volumes:
      - config:/config
    labels:
      io.balena.features.kernel-modules: '1'
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
