version: "2.1"

volumes:
  config:

services:
  wireguard:
    build: .
    privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_MODULE
    volumes:
      - config:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - io.balena.features.kernel-modules=1
      - io.balena.features.supervisor-api=1
