version: "2.1"

volumes:
  config:

services:
  web:
    image: vx3r/wg-gen-web:latest
    ports:
      - 80:8080/tcp
    volumes:
      - config:/data
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf

  userspace:
    build: userspace
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - config:/etc/wireguard

  module:
    build: module
    cap_add:
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: '1'
    restart: on-failure
