name: version

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master
      - main

env:
  DRAFT: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: ${{ env.DRAFT }}

      - name: Set balena.yml version
        if: github.ref == 'refs/heads/main'
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i -v '.version = "${{ steps.tag_version.outputs.new_version }}"' 'balena.yml'

      - name: Checkout balena-io/balena-ci
        uses: actions/checkout@v2
        with:
          repository: balena-io/balena-ci
          ref: refs/heads/master
          token: ${{ secrets.BALENA_CI_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/balena-ci

      - uses: ./.github/actions/balena-ci
        id: balena-ci
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: ${{ secrets.BALENA_FLEET }}
      
      - name: Log release ID
        run: echo "Pushed release ID ${{ steps.build.outputs.release_id }}"
